<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>DayZServerManager</AssemblyName>
    <RootNamespace>DayZServerManager</RootNamespace>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>1.0.0</Version>
    <Product>Stryxhost Manager</Product>
    <AssemblyTitle>Stryxhost Manager</AssemblyTitle>
    <Description>Stryxhost Manager - le gestionnaire de serveurs DayZ</Description>
    <Company>Spadeure</Company>
    <Authors>Spadeure</Authors>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\app.ico" />
    <Resource Include="Assets\icon.png" />
    <Resource Include="Assets\logo.png" />
    <Resource Include="Fonts\Orbitron-Bold.ttf" />
  </ItemGroup>

</Project>
